<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120715232951 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE Award (id INT AUTO_INCREMENT NOT NULL, receiving_member_id INT DEFAULT NULL, approving_member_id INT DEFAULT NULL, earned DATE NOT NULL, awarded DATE NOT NULL, value INT NOT NULL, type VARCHAR(255) NOT NULL, category VARCHAR(255) NOT NULL, description VARCHAR(1023) NOT NULL, note VARCHAR(1023) NOT NULL, INDEX IDX_4B9A01E37AAEC7F5 (receiving_member_id), INDEX IDX_4B9A01E37D0C9749 (approving_member_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("ALTER TABLE Award ADD CONSTRAINT FK_4B9A01E37AAEC7F5 FOREIGN KEY (receiving_member_id) REFERENCES Member(id)");
        $this->addSql("ALTER TABLE Award ADD CONSTRAINT FK_4B9A01E37D0C9749 FOREIGN KEY (approving_member_id) REFERENCES Member(id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("DROP TABLE Award");
    }
}
