<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120626223319 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE Award (id INT AUTO_INCREMENT NOT NULL, earned DATE NOT NULL, type VARCHAR(255) NOT NULL, category VARCHAR(255) NOT NULL, amount INT NOT NULL, description VARCHAR(1023) NOT NULL, note VARCHAR(1023) DEFAULT NULL, awarded DATE NOT NULL, member_number VARCHAR(255) NOT NULL, PRIMARY KEY(id)) ENGINE = InnoDB");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("DROP TABLE Award");
    }
}
