<?php

namespace MindsEyeSociety\ReportBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AwardRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AwardRepository extends EntityRepository
{
}