parameters:
#    minds_eye_society_library.example.class: MindsEyeSociety\LibraryBundle\Example

services:
#    minds_eye_society_library.example:
#        class: %minds_eye_society_library.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
